### ISSUE TITLE
Zero-argument function definition missing for plot()

### ISSUE THREAD

**Issue by arturgower** [GiovineItalia/Gadfly.jl#947] opened 2017-01-09 15:33 UTC
`plot()`
returns: 
`ERROR: The following aesthetics are required by Geom.point but are not defined: y, x` 

This is an old issue, mentioned [here](https://github.com/tbreloff/Plots.jl/issues/73), when Gadfly was used as a backed to Plots. What is the current work around?

What I really want to do is plot circles where the radius is in the same coordinates as the position of the circles. Something that can not easily be done in the package Plots. That is,

`using Gadfly, Compose`
`pc = Guide.annotation(compose(context(), circle([2,4], [2,4], [sqrt(8)/2])))`
`plot(pc)`

One solution is to specify `y,x`:

`p1=layer(x=1:10,y=1:10, Geom.point())`
`plot(p1,ps, Coord.cartesian(fixed=true))`

where `Coord.cartesian(fixed=true)` is passed so that the circles have the correct dimension.

Gadfly is a great package, so thanks to all who help develop it! So I'm wondering, several of these issues are from around 1 year ago, has development slowed down?

**Comment by tlnagy** [comment] 2017-01-09 23:02
Development has slowed down since @dcjones (the original author) transitioned to other things. I've stepped in recently as a basic maintainer to fix critical bugs because I'm using Gadfly in some of my projects, but I (and other contributors) are graduate students and have less time than we would like to fix all the bugs that accumulate. I am, however, happy to review and work with you to fix bugs if you are interested in helping this project along :) 

I can reproduce your error on Julia v0.5 with the latest Gadfly. Looks like Tom's fix wasn't merged or was broken later.

**Comment by arturgower** [comment] 2017-01-10 20:05
Thanks for answering quickly. And I can totally appreciate the lack of time, I myself am a post-doc.  Yes I want to help. I am new to all this (I know very basic git), so bug tracking seems like a good place to start. I've created a local branch "bug/947" and am now trying to work out the basics.

**Comment by tlnagy** [comment] 2017-01-10 21:42
Thanks! Have you contributed to a Julia package before? The following reference is helpful in getting everything set up: http://docs.julialang.org/en/stable/manual/packages/#making-changes-to-an-existing-package

**Closed** 2019-11-17 13:09 UTC
Labels: enhancement
