### ISSUE TITLE
_jl_libpangocairo not defined

### ISSUE THREAD

**Issue by gustafsson** [GiovineItalia/Gadfly.jl#935] opened 2016-11-29 15:38 UTC
I'm trying to get the PNG backend to work, so I installed Cairo.jl. But `using Gadfly` fails with Cairo.jl installed.

```
~/.julia$ rm -rf ~/Library/Caches/Homebrew.jl v0.5 lib/v0.5
~/.julia$ julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0 (2016-09-19 18:14 UTC)
 _/ |\__'_|_|_|\__'_|  |  
|__/                   |  x86_64-apple-darwin15.6.0

julia> Pkg.add("Gadfly")
INFO: Initializing package repository ~/.julia/v0.5
INFO: Cloning METADATA from https://github.com/JuliaLang/METADATA.jl
INFO: Installing AxisAlgorithms v0.1.5
[... omitted ...]
INFO: Package database updated

julia> using Gadfly
INFO: Precompiling module Gadfly.

julia> plot(x=1:10,y=1:10)
```
So far so good. Gadfly is installed on a clean Julia installation. I then try to use the PNG backend:
``` 
julia> draw(PNG(25cm, 10cm), plot(x=1:10,y=1:10))
ERROR: Cairo and Fontconfig are necessary for the PNG backend. Run:
  Pkg.add("Cairo")
  Pkg.add("Fontconfig")
You also have to delete ~/.julia/lib/v0.5/Compose.ji
and restart your REPL session afterwards.

 in PNG(::Measures.Length{:mm,Float64}, ::Vararg{Measures.Length{:mm,Float64},N}) at ~/.julia/v0.5/Compose/src/Compose.jl:182
```
I then install those as requested and delete that precompiled `Compose.jl`.
```
julia> Pkg.add("Cairo")
INFO: Installing Cairo v0.2.35
INFO: Installing Graphics v0.1.3
INFO: Installing Homebrew v0.4.1
INFO: Building Homebrew
INFO: Downloading brew...
######################################################################## 100.0%
Initialized empty Git repository in ~/.julia/v0.5/Homebrew/deps/usr/.git/
[... omitted ...]
INFO: Package database updated

julia> Pkg.add("Fontconfig")
INFO: Installing Fontconfig v0.1.1
INFO: Building Homebrew
Already up-to-date.
INFO: Building Fontconfig
INFO: Package database updated

~/.julia$ rm ~/.julia/lib/v0.5/Compose.ji
```
But now `using Gadfly` won't work. I don't even get to the point where I can try if the PNG backend works.
```
~/.julia$ julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0 (2016-09-19 18:14 UTC)
 _/ |\__'_|_|_|\__'_|  |  
|__/                   |  x86_64-apple-darwin15.6.0

julia> using Gadfly
INFO: Precompiling module Compose.
Fontconfig error: Cannot load default config file
ERROR: LoadError: LoadError: UndefVarError: _jl_libpangocairo not defined
 in include_from_node1(::String) at ./loading.jl:488
 in include_from_node1(::String) at /usr/local/Cellar/julia/0.5.0/lib/julia/sys.dylib:?
 in include_from_node1(::String) at ./loading.jl:488
 in include_from_node1(::String) at /usr/local/Cellar/julia/0.5.0/lib/julia/sys.dylib:?
 in macro expansion; at ./none:2 [inlined]
 in anonymous at ./<missing>:?
 in eval(::Module, ::Any) at ./boot.jl:234
 in eval(::Module, ::Any) at /usr/local/Cellar/julia/0.5.0/lib/julia/sys.dylib:?
 in process_options(::Base.JLOptions) at ./client.jl:239
 in _start() at ./client.jl:318
 in _start() at /usr/local/Cellar/julia/0.5.0/lib/julia/sys.dylib:?
while loading ~/.julia/v0.5/Compose/src/pango.jl, in expression starting on line 6
while loading ~/.julia/v0.5/Compose/src/Compose.jl, in expression starting on line 194
ERROR: Failed to precompile Compose to ~/.julia/lib/v0.5/Compose.ji.
 in compilecache(::String) at ./loading.jl:593
 in require(::Symbol) at ./loading.jl:422
 in require(::Symbol) at /usr/local/Cellar/julia/0.5.0/lib/julia/sys.dylib:?
 in _include_from_serialized(::String) at ./loading.jl:150
 in _require_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at ./loading.jl:187
 in _require_search_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at ./loading.jl:217
 in _require_search_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at /usr/local/Cellar/julia/0.5.0/lib/julia/sys.dylib:?
 in require(::Symbol) at ./loading.jl:371
 in require(::Symbol) at /usr/local/Cellar/julia/0.5.0/lib/julia/sys.dylib:?
```

Any ideas?

**Comment by gustafsson** [comment] 2016-11-29 16:06
For anyone else having this issue. This old solution https://github.com/JuliaPackaging/Homebrew.jl/issues/59#issuecomment-55130516 seems to have solved this:
```
Pkg.add("Cairo")
Pkg.add("Fontconfig")
using Homebrew
Homebrew.rm("libpng")
Homebrew.add("libpng")
Homebrew.rm("cairo")
Homebrew.add("cairo")
Homebrew.rm("pango")
Homebrew.add("pango")
Pkg.build("Cairo")
using Gadfly
```

Still, Gadfly currently doesn't work with the PNG backend without this fix on a clean installation.

Since this fix shouldn't be needed on a clean install I'm leaving the issue open, but this might be a bug with `Cairo.jl` rather than Gadfly.

**Comment by lobingera** [comment] 2016-11-29 17:30
I see this as mixture of BinDeps and Homebrew bug. Cairo is working correctly if the libraries are installed and found...

**Comment by gustafsson** [comment] 2016-11-30 11:02
@lobingera so if I'm starting from a fresh install of Julia (as I did here), are you aware of a way to get PNG working without the hack I presented above?

**Comment by lobingera** [comment] 2016-11-30 18:08
I think this should be in https://github.com/GiovineItalia/Gadfly.jl/issues/936

**Comment by gustafsson** [comment] 2016-11-30 19:23
I've presented poor workarounds for both issues. Either hack shouldn't be necessary.

**Comment by tlnagy** [comment] 2016-11-30 21:11
Yeah, I've run into intermittent issues with Cairo install via `Homebrew.jl` where there are problems with precompilation. I haven't been able to reproduce it regularly, but it pops up now and again, unfortunately. Not sure what the best way of approaching this is.

**Comment by aviks** [comment] 2017-01-17 22:16
I just hit exactly this issue, and @gustafsson 's workaround above worked.

**Comment by tlnagy** [comment] 2017-01-30 05:56
I'm closing this for now due to inability to diagnose this consistently. If people keep running into this then we can open this back up.

**Closed by tlnagy** 2017-01-30 05:56 UTC
