### ISSUE TITLE
Error on calling plot() function of Gadfly from Julia REPL

### ISSUE THREAD

**Issue by sushantupadhyay** [GiovineItalia/Gadfly.jl#783] opened 2016-01-07 13:29 UTC
Hi ,
I tried to execute an example in the Gadfly manual and it threw an error. Other examples work fine.
I am using Windows 7 ( 32 bit).
I have installed Julia , all concerned packages just a an hour ago.
I am sending 
1. the code
2. The error thrown
3 the list of packages installed
 in that order.
Please help

CODE:

julia> using RDatasets
julia>using Gadfly
julia> plot(dataset("car", "SLID"), x="Wages", color="Language", Geom.histogram)

ERROR:

Error showing value of type Gadfly.Plot:
ERROR: MethodError: `hash` has no method matching hash(::Compose.FillPrimitive, ::UInt64)
Closest candidates are:
  hash(::ANY, ::UInt32)
  hash(::Compose.FontPrimitive, ::UInt64)
  hash(::Compose.SVGIDPrimitive, ::UInt64)
  ...
 in optimize_batching at C:\Users\Rekha.julia\v0.4\Compose\src\batch.jl:210
 in resize! at array.jl:465
 in drawpart at C:\Users\Rekha.julia\v0.4\Compose\src\container.jl:586 (repeats 4 times)

LIST OF PACKAGES:
  "Reexport"          => v"0.0.3"
  "DualNumbers"       => v"0.2.0"
  "Grid"              => v"0.4.0"
  "Measures"          => v"0.0.1"
  "KernelDensity"     => v"0.1.2"
  "ImmutableArrays"   => v"0.0.11"
  "Compat"            => v"0.7.8"
  "FixedPointNumbers" => v"0.1.1"
  "ArrayViews"        => v"0.6.4"
  "StatsBase"         => v"0.7.4"
  "Docile"            => v"0.5.22"
  "StatsFuns"         => v"0.2.0"
  "Graphics"          => v"0.1.3"
  "Gadfly"            => v"0.4.0"
  "PyCall"            => v"1.2.0"
  "Contour"           => v"0.0.8"
  "Iterators"         => v"0.1.9"
  "Codecs"            => v"0.1.5"
  "BinDeps"           => v"0.3.20"
  "URIParser"         => v"0.1.2"
  "Cairo"             => v"0.2.31"
  "Distributions"     => v"0.8.8"
  "PDMats"            => v"0.3.6"
  "SHA"               => v"0.1.2"
  "DataStructures"    => v"0.4.1"
  "LsqFit"            => v"0.0.2"
  "Showoff"           => v"0.0.6"
  "Loess"             => v"0.0.6"
  "GZip"              => v"0.2.18"
  "RDatasets"         => v"0.1.2"
  "NaNMath"           => v"0.1.1"
  "Zlib"              => v"0.1.12"
  "Conda"             => v"0.1.8"
  "Compose"           => v"0.4.0"
  "Optim"             => v"0.4.4"
  "WinRPM"            => v"0.1.13"
  "DataFrames"        => v"0.6.10"
  "WoodburyMatrices"  => v"0.1.3"
  "Calculus"          => v"0.1.14"
  "ColorTypes"        => v"0.2.0"
  "GLM"               => v"0.4.8"
  "Dates"             => v"0.4.4"
  "JSON"              => v"0.5.0"
  "SortingAlgorithms" => v"0.0.6"
  "Hexagons"          => v"0.0.4"
  "DataArrays"        => v"0.2.20"
  "Colors"            => v"0.6.1"
  "Distances"         => v"0.3.0"
  "LibExpat"          => v"0.1.0"

**Comment by rohitvarkey** [comment] 2016-01-07 15:21
I can't reproduce this even though I have the same Gadfly and Compose versions.

**Comment by trohwer** [comment] 2017-04-12 14:48
I have a similar error and fixed it (for me). Some of the hash functions, e.g. the following in property.jl

function Base.hash(primitive::SVGClassPrimitive, h::UInt64)
    return hash(primitive.value, h)
end

are declared with the type UInt64. But the standard hash function, which is called, is
declared with UInt, which is different depending on the architecture (32bit or 64bit).

So in case of a 32bit architecture, the call to hash(primitive,h) does not seem to match.

I changed all the relevant UInt64 in the module to UInt, and now it is working for me.

**Comment by tlnagy** [comment] 2017-04-12 16:47
@trohwer If you want to submit a PR, I would be happy to review it. The types for those functions should probably be `UInt` as you point out.

**Comment by trohwer** [comment] 2017-04-12 17:16
I forgot to mention, that the problem is not in the Gadfly project, but in the Compose project.

I am not familiar with generating a PR and Git in general yet. If it is not too difficult, I will do it.

**Comment by bjarthur** [comment] 2017-08-11 17:54
fixed by **https://github.com/GiovineItalia/Compose.jl/pull/243**

**Closed by bjarthur** 2017-08-11 17:54 UTC
