### ISSUE TITLE
Tests are still failing on PkgEval

### ISSUE THREAD

**Issue by tlnagy** [GiovineItalia/Gadfly.jl#1109] opened 2018-03-16 20:55 UTC
It's really unfortunate that our whole README is full of fail

![image](https://user-images.githubusercontent.com/1661487/37543796-02b135de-2920-11e8-9f5f-c3d81863a7be.png)

We should be passing on PkgEval at the minimum. We should also consider switching to allowing failures on top of Julia nightlies on Travis after 0.7 comes out since it just makes us look bad.

Looking through the [log](https://pkg.julialang.org/logs/Gadfly_0.6.log), it appears as though `PkgEval` can't open the files:

```julia
ERROR: LoadError: InitError: Cannot open display: 
Stacktrace:
 [1] Gtk.GLib.GError(::Gtk.##229#230) at /home/vagrant/.julia/v0.6/Gtk/src/GLib/gerror.jl:17
 [2] __init__() at /home/vagrant/.julia/v0.6/Gtk/src/events.jl:10
 [3] _include_from_serialized(::String) at ./loading.jl:157
 [4] _require_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at ./loading.jl:200
 [5] _require(::Symbol) at ./loading.jl:464
 [6] require(::Symbol) at ./loading.jl:405
 [7] include_from_node1(::String) at ./loading.jl:576
 [8] include(::String) at ./sysimg.jl:14
 [9] anonymous at ./<missing>:2
during initialization of module Gtk
while loading /home/vagrant/.julia/v0.6/Rsvg/src/Rsvg.jl, in expression starting on line 9
ERROR: LoadError: Failed to precompile Rsvg to /home/vagrant/.julia/lib/v0.6/Rsvg.ji.
Stacktrace:
 [1] compilecache(::String) at ./loading.jl:710
 [2] _require(::Symbol) at ./loading.jl:497
 [3] require(::Symbol) at ./loading.jl:405
 [4] include_from_node1(::String) at ./loading.jl:576
 [5] include(::String) at ./sysimg.jl:14
 [6] process_options(::Base.JLOptions) at ./client.jl:305
 [7] _start() at ./client.jl:371
while loading /home/vagrant/.julia/v0.6/Gadfly/test/compare_examples.jl, in expression starting on line 1
ERROR: LoadError: failed process: Process(`/home/vagrant/julia/bin/julia -Cx86-64 -J/home/vagrant/julia/lib/julia/sys.so --compile=yes --depwarn=yes compare_examples.jl`, ProcessExited(1)) [1]
Stacktrace:
 [1] pipeline_error(::Base.Process) at ./process.jl:682
 [2] run(::Cmd) at ./process.jl:651
 [3] include_from_node1(::String) at ./loading.jl:576
 [4] include(::String) at ./sysimg.jl:14
 [5] process_options(::Base.JLOptions) at ./client.jl:305
 [6] _start() at ./client.jl:371
while loading /home/vagrant/.julia/v0.6/Gadfly/test/runtests.jl, in expression starting on line 118
===============================[ ERROR: Gadfly ]================================

failed process: Process(`/home/vagrant/julia/bin/julia -Cx86-64 -J/home/vagrant/julia/lib/julia/sys.so --compile=yes --depwarn=yes --check-bounds=yes --code-coverage=none --color=no --compilecache=yes /home/vagrant/.julia/v0.6/Gadfly/test/runtests.jl`, ProcessExited(1)) [1]

================================================================================
```

I don't see why it's trying to open the files?

**Comment by bjarthur** [comment] 2018-03-16 22:01
it used to open files when regression testing was done automatically.  we haven't tagged a release since that was changed.

**Comment by tlnagy** [comment] 2018-03-16 22:09
What are your thoughts on testing the nightlies on Travis?

> we haven't tagged a release since that was changed.

Do you want to wait till #1037 and #1090 are merged to do this?

**Comment by bjarthur** [comment] 2018-03-16 23:32
i just merged #1037.  what do you think of tagging a release now, before julia 0.5 support is dropped by #1090.  then tagging another after that is merged?  not many folks using 0.5 i'm guessing but it would be nice to give them a release which includes all the latest PRs.

**Comment by bjarthur** [comment] 2018-03-16 23:34
re. testing nightlies...  i liked your idea of stopping that as soon as 0.7 comes out.

**Comment by bjarthur** [comment] 2018-03-17 00:03
better yet, let's test on nightly but allow failures and finish fast:  https://github.com/JuliaMath/Polynomials.jl/blob/master/.travis.yml#L8

**Comment by tlnagy** [comment] 2018-03-17 00:11
Yeah, allowing failures is what I meant.

**Comment by tlnagy** [comment] 2018-03-17 00:12
I think your tagging strategy sounds good. Lets give them the enhanced activity and other improvements and then drop 0.5 support.

**Comment by bjarthur** [comment] 2018-06-22 11:33
green badge!  https://pkg.julialang.org/?pkg=Gadfly#Gadfly

**Closed by bjarthur** 2018-06-22 11:33 UTC
