### ISSUE TITLE
BoundsError with group aesthetic

### ISSUE THREAD

**Issue by jotwin** [GiovineItalia/Gadfly.jl#967] opened 2017-03-14 18:06 UTC
works with color = :i  but not with group = :i

```
 plot(baddf, x=:phi, y=:fhat, group=:i, Geom.line)
Error showing value of type Gadfly.Plot:
ERROR: BoundsError: attempt to access 1-element Array{UInt32,1} at index [4]
 in permute!!(::Array{UInt32,1}, ::Array{Int64,1}) at ./combinatorics.jl:86
 in permute!! at /home/jakub/.julia/v0.5/DataArrays/src/pooleddataarray.jl:452 [inlined]
 in permute!(::DataArrays.PooledDataArray{ColorTypes.RGBA{Float32},UInt32,1}, ::Array{Int64,1}) at ./combinatorics.jl:107
 in render(::Gadfly.Geom.LineGeometry, ::Gadfly.Theme, ::Gadfly.Aesthetics) at /home/jakub/.julia/v0.5/Gadfly/src/geom/line.jl:112
 in render(::Gadfly.Geom.LineGeometry, ::Gadfly.Theme, ::Gadfly.Aesthetics, ::Array{Gadfly.Aesthetics,1}, ::Array{Gadfly.Data,1}, ::Dict{Symbol,Gadfly.ScaleElement}) at /home/jakub/.julia/v0.5/Gadfly/src/geometry.jl:48
 in (::Gadfly.##113#115{Dict{Symbol,Gadfly.ScaleElement}})(::Tuple{Gadfly.Layer,Gadfly.Aesthetics,Array{Gadfly.Aesthetics,1},Array{Gadfly.Data,1},Gadfly.Theme}) at ./<missing>:0
 in collect(::Base.Generator{Zip{Array{Gadfly.Layer,1},Zip{Array{Gadfly.Aesthetics,1},Zip{Array{Array{Gadfly.Aesthetics,1},1},Base.Zip2{Array{Array{Gadfly.Data,1},1},Array{Gadfly.Theme,1}}}}},Gadfly.##113#115{Dict{Symbol,Gadfly.ScaleElement}}}) at ./array.jl:307
 in #render_prepared#111(::Bool, ::Bool, ::Function, ::Gadfly.Plot, ::Gadfly.Coord.Cartesian, ::Gadfly.Aesthetics, ::Array{Gadfly.Aesthetics,1}, ::Array{Array{Gadfly.StatisticElement,1},1}, ::Array{Array{Gadfly.Aesthetics,1},1}, ::Array{Array{Gadfly.Data,1},1}, ::Dict{Symbol,Gadfly.ScaleElement}, ::Array{Gadfly.GuideElement,1}) at /home/jakub/.julia/v0.5/Gadfly/src/Gadfly.jl:888
 in render_prepared(::Gadfly.Plot, ::Gadfly.Coord.Cartesian, ::Gadfly.Aesthetics, ::Array{Gadfly.Aesthetics,1}, ::Array{Array{Gadfly.StatisticElement,1},1}, ::Array{Array{Gadfly.Aesthetics,1},1}, ::Array{Array{Gadfly.Data,1},1}, ::Dict{Symbol,Gadfly.ScaleElement}, ::Array{Gadfly.GuideElement,1}) at /home/jakub/.julia/v0.5/Gadfly/src/Gadfly.jl:877
 in render(::Gadfly.Plot) at /home/jakub/.julia/v0.5/Gadfly/src/Gadfly.jl:823
 in display(::Base.REPL.REPLDisplay{Base.REPL.LineEditREPL}, ::MIME{Symbol("text/html")}, ::Gadfly.Plot) at /home/jakub/.julia/v0.5/Gadfly/src/Gadfly.jl:1113
 in macro expansion at ./multimedia.jl:143 [inlined]
 in display(::Gadfly.Plot) at /home/jakub/.julia/v0.5/Gadfly/src/Gadfly.jl:1065
 in hookless(::Media.##7#8{Gadfly.Plot}) at /home/jakub/.julia/v0.5/Media/src/compat.jl:14
 in render(::Media.NoDisplay, ::Gadfly.Plot) at /home/jakub/.julia/v0.5/Media/src/compat.jl:27
 in display(::Media.DisplayHook, ::Gadfly.Plot) at /home/jakub/.julia/v0.5/Media/src/compat.jl:9
 in macro expansion at ./multimedia.jl:143 [inlined]
 in display(::Gadfly.Plot) at /home/jakub/.julia/v0.5/Gadfly/src/Gadfly.jl:1069
 in print_response(::Base.Terminals.TTYTerminal, ::Any, ::Void, ::Bool, ::Bool, ::Void) at ./REPL.jl:154
 in print_response(::Base.REPL.LineEditREPL, ::Any, ::Void, ::Bool, ::Bool) at ./REPL.jl:139
 in (::Base.REPL.##22#23{Bool,Base.REPL.##33#42{Base.REPL.LineEditREPL,Base.REPL.REPLHistoryProvider},Base.REPL.LineEditREPL,Base.LineEdit.Prompt})(::Base.LineEdit.MIState, ::Base.AbstractIOBuffer{Array{UInt8,1}}, ::Bool) at ./REPL.jl:652
 in (::Base.REPL.##38#47)(::Base.LineEdit.MIState, ::Base.REPL.LineEditREPL, ::Vararg{Any,N}) at ./REPL.jl:867
 in (::Base.LineEdit.##13#14{Base.REPL.##38#47,String})(::Base.LineEdit.MIState, ::Base.REPL.LineEditREPL) at ./LineEdit.jl:736
 in run_repl(::Base.REPL.LineEditREPL, ::Base.##930#931) at ./REPL.jl:188
```

**Comment by bjarthur** [comment] 2017-03-14 18:19
make a [gist](https://gist.github.com/) with baddf so we can try to replicate

**Comment by jotwin** [comment] 2017-03-14 18:24
https://gist.github.com/jotwin/419c436b729f4cab943cfec8957922c1

**Comment by bjarthur** [comment] 2017-03-14 18:58
i can reproduce.  what would you expect the group aesthetic to do?

**Comment by jotwin** [comment] 2017-03-14 19:03
Its to make a line for each i, instead of making one long line. 
group aesthetic works just like the color aesthetic, except they should all have default color.

**Comment by bjarthur** [comment] 2017-03-17 11:25
@tlnagy could you please comment on this?

the crash occurs on https://github.com/GiovineItalia/Gadfly.jl/blob/master/src/geom/line.jl#L117 when the group aesthetic and line geometry are specified.

with the gist above, `length(aes.color)` is 1 and `length(aes.group)` is 4.

what i don't understand is how, with the group aesthetic specified, could the color length ever be more than 1.  yet https://github.com/GiovineItalia/Gadfly.jl/blob/master/src/geom/line.jl#L111 handles this case.

more generally, there is a lot of code duplication between the cases that the group aesthetic is present (https://github.com/GiovineItalia/Gadfly.jl/blob/master/src/geom/line.jl#L91) and the color aethetic is present (https://github.com/GiovineItalia/Gadfly.jl/blob/master/src/geom/line.jl#L166).  these two are mutually exclusive, no?  there is probably an opportunity for simplification here.

**Comment by tlnagy** [comment] 2017-03-21 17:34
Sorry I wasn't able to get around this quicker. I think they should be mutually exclusive. And yeah, generally, there is a lot of code duplication in Gadfly code base. It would be great to eliminate a lot of that. 👍

**Comment by tlnagy** [comment] 2017-03-21 17:37
The only example test with the `group` aesthetic that I could find is this one: https://github.com/GiovineItalia/Gadfly.jl/blob/63a0c28af8fbbb8d88857159d6b0b779dc65f024/test/polygon.jl, which doesn't help since it doesn't have a color specified. I suspect the best way forward is to enforce that each group has a unique color and then ignore (or disable) the color aesthetic. 

Would that work for your problem @jotwin ?

**Comment by jotwin** [comment] 2017-03-21 19:42
I'm not sure what you're suggesting. The lines should appear in groups specified by the group aesthetic, all with the same default color. They should NOT be grouped and have different colors, because thats what the color aesthetic does.

**Comment by tlnagy** [comment] 2017-03-21 21:08
Good point. Yeah, then I would expect them to be mutually exclusive.

**Comment by Mattriks** [comment] 2017-03-21 21:58
For the record, the `group` aesthetic works:
```julia
D = vcat([DataFrame(x=1.0:10.0, y=i*10+(1:10), i=i) for i in 1:3]...)
p = plot(D, x=:x, y=:y, group=:i, Geom.line)
```
The issue in the original issue seems to be that it does not work in all cases (e.g. with the above `phi`, `fhat` data), but why is yet to be diagnosed.

**Comment by bjarthur** [comment] 2018-08-21 11:08
fixed by https://github.com/GiovineItalia/Gadfly.jl/pull/1181

**Closed by bjarthur** 2018-08-21 11:08 UTC
