### ISSUE TITLE
Deprecated msg, in DataFrames 0.19: getindex(df::DataFrame, col_ind::ColumnIndex)` is deprecated, use `df[!, col_ind]

### ISSUE THREAD

**Issue by dmolina** [GiovineItalia/Gadfly.jl#1312] opened 2019-09-08 14:24 UTC
When I try to plot a DataFrame it gives me:

Warning: `getindex(df::DataFrame, col_ind::ColumnIndex)` is deprecated, use `df[!, col_ind]` instead.
│   caller = evalmapping(::DataFrame, ::Symbol) at dataframes.jl:96
└ @ Gadfly ~/.julia/packages/Gadfly/09PWZ/src/dataframes.jl:96

In DataFrames 0.19 the access with only one parameter, the column, is deprecated, you can use df[:,col] (to return a copy) or df[!, col] (to return a view).

I am going to propose a pull request to solve it.

**Comment by Mattriks** [comment] 2019-09-09 00:11
Duplicate of #1304

**Comment by tlnagy** [comment] 2019-09-10 00:33
I'm going to close this in lieu of #1304

**Closed by tlnagy** 2019-09-10 00:33 UTC
