### ISSUE TITLE
ERROR: Failed to precompile Gadfly - julia 1.0

### ISSUE THREAD

**Issue by jcbritobr** [GiovineItalia/Gadfly.jl#1198] opened 2018-09-30 12:51 UTC
Gadfly is faling to precompile in julia 1.0

host os - ubuntu 18.04 x64
julia version - 1.0

```
julia> using Gadfly
[ Info: Precompiling Gadfly [c91e804a-d5a3-530f-b6f0-dfbca275c004]


ERROR: LoadError: LoadError: UndefVarError: start not defined
Stacktrace:
 [1] getproperty(::Module, ::Symbol) at ./sysimg.jl:13
 [2] top-level scope at none:0
 [3] include at ./boot.jl:317 [inlined]
 [4] include_relative(::Module, ::String) at ./loading.jl:1038
 [5] include at ./sysimg.jl:29 [inlined]
 [6] include(::String) at /home/jgardona/.julia/packages/DataArrays/mcLPH/src/DataArrays.jl:3
 [7] top-level scope at none:0
 [8] include at ./boot.jl:317 [inlined]
 [9] include_relative(::Module, ::String) at ./loading.jl:1038
 [10] include(::Module, ::String) at ./sysimg.jl:29
 [11] top-level scope at none:2
 [12] eval at ./boot.jl:319 [inlined]
 [13] eval(::Expr) at ./client.jl:389
 [14] top-level scope at ./none:3
in expression starting at /home/jgardona/.julia/packages/DataArrays/mcLPH/src/abstractdataarray.jl:27
in expression starting at /home/jgardona/.julia/packages/DataArrays/mcLPH/src/DataArrays.jl:45
ERROR: LoadError: Failed to precompile DataArrays [0fe7c1db-08c2-54a3-a222-6d1d3b7a471a] to /home/jgardona/.julia/compiled/v1.0/DataArrays/ZAWTY.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] macro expansion at ./logging.jl:313 [inlined]
 [3] compilecache(::Base.PkgId, ::String) at ./loading.jl:1184
 [4] _require(::Base.PkgId) at ./logging.jl:311
 [5] require(::Base.PkgId) at ./loading.jl:852
 [6] macro expansion at ./logging.jl:311 [inlined]
 [7] require(::Module, ::Symbol) at ./loading.jl:834
 [8] include at ./boot.jl:317 [inlined]
 [9] include_relative(::Module, ::String) at ./loading.jl:1038
 [10] include(::Module, ::String) at ./sysimg.jl:29
 [11] top-level scope at none:2
 [12] eval at ./boot.jl:319 [inlined]
 [13] eval(::Expr) at ./client.jl:389
 [14] top-level scope at ./none:3
in expression starting at /home/jgardona/.julia/packages/Gadfly/p8TXc/src/Gadfly.jl:8
ERROR: Failed to precompile Gadfly [c91e804a-d5a3-530f-b6f0-dfbca275c004] to /home/jgardona/.julia/compiled/v1.0/Gadfly/DvECm.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] macro expansion at ./logging.jl:313 [inlined]
 [3] compilecache(::Base.PkgId, ::String) at ./loading.jl:1184
 [4] _require(::Base.PkgId) at ./logging.jl:311
 [5] require(::Base.PkgId) at ./loading.jl:852
 [6] macro expansion at ./logging.jl:311 [inlined]
 [7] require(::Module, ::Symbol) at ./loading.jl:834
```

**Comment by fabmazz** [comment] 2018-09-30 19:49
This happens to me too, exactly the same error. As you can see, the problem is in the package "DataArrays", but by looking at https://github.com/JuliaStats/DataArrays.jl/issues/306 it seems that DataArrays should not be used anymore... waiting to get an answer from the devs!

**Comment by Mattriks** [comment] 2018-09-30 20:03
Works for me - I'm on `Gadfly#master`:
https://discourse.julialang.org/t/julia-1-0-support-just-landed-on-gadfly-master/14978
Also check that you have `Compose 0.7`.  Compose 0.7 was tagged recently, so you don't need to be on Compose#master.

**Comment by fabmazz** [comment] 2018-09-30 20:08
I do have Compose 0.7.0 installed (done automatically by the package
manager with the tags).

Il Dom 30 Set 2018, 22:03 Mattriks <notifications@github.com> ha scritto:

**Comment by Mattriks** [comment] 2018-09-30 20:27
If you are still having issues than please provide:
```julia
versioninfo()
using Pkg; Pkg.status()
```

**Comment by fabmazz** [comment] 2018-09-30 20:34
```julia> versioninfo()
Julia Version 1.0.0
Commit 5d4eaca0c9 (2018-08-08 20:58 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, skylake)

julia> using Pkg; Pkg.status()
    Status `~/.julia/environments/v1.0/Project.toml`
  [7d9fca2a] Arpack v0.2.3+ [`~/.julia/dev/Arpack`]
  [c52e3926] Atom v0.7.7
  [a93c6f00] DataFrames v0.14.0
  [c91e804a] Gadfly v0.8.0
  [a1b4810d] Hexagons v0.2.0
  [7073ff75] IJulia v1.12.0
  [e5e0dc1b] Juno v0.5.3
  [d330b81b] PyPlot v2.6.3
```

**Comment by Mattriks** [comment] 2018-09-30 20:41
Now do:
```
pkg"add Gadfly#master"
```

**Comment by fabmazz** [comment] 2018-09-30 20:57
worked

```
julia> using Gadfly
[ Info: Precompiling Gadfly [c91e804a-d5a3-530f-b6f0-dfbca275c004]
WARNING: using Gadfly.hexagon in module Main conflicts with an existing identifier.
```

thank you a lot

**Comment by tlnagy** [comment] 2018-10-01 05:37
We'll be tagging a new release for Gadfly in the near future so this extra step won't be necessary.

**Closed by tlnagy** 2018-10-01 05:37 UTC
