### ISSUE TITLE
X-axis borked for date data, can't seem to override

### ISSUE THREAD

**Issue by IainNZ** [GiovineItalia/Gadfly.jl#784] opened 2016-01-08 21:15 UTC
Check out http://pkg.julialang.org/pulse.html

The data spans multiple years, and once it went into 2016 the ticks become annual. I tried to override with `Scale.x_continuous` with the minvalue and maxvalue being set to specific dates, but it seemed to be ignored.

e.g.

```
x_vals = [(Date(2014,2,1) + Dates.Day(i)) for i in 1:700]
y_vals = [i for i in 1:700]
plot(x=x_vals, y=y_vals, Geom.line)
```

shows the not-so-smart x-axis, and
`Scale.x_continuous(minvalue=Date(2014,1,1),maxvalue=Date(2016,2,1))`
is ignored

**Comment by timholy** [comment] 2016-01-08 21:31
Oof.

FYI, folks seem to be a bit on their own these days with respect to Gadfly/Compose. So a PR fixing it would be even better!

**Comment by IainNZ** [comment] 2016-01-08 21:34
Yeah I figured. I think I don't have the time to spend to familiarize myself with this enough to fix it, but, holding out hope these is some hack or work around. Might have to switch to PyPlot for the package listing.

**Comment by amellnik** [comment] 2016-01-13 17:33
@IanNZ I had the exact same thing happen when I came back from New Years.  The problem is ticks always override any limits set in Scale.x_continuous  My workaround was to define 

```julia
import Gadfly.optimize_ticks
function TightTicks(data::AbstractArray)
    tmin = minimum(data)
    tmax = maximum(data)
    ticks, trash = Gadfly.optimize_ticks(tmin, tmax)
    ticks = ticks[(ticks.<=tmax)&(ticks.>=tmin)]
end
```

and when I call plot to use 

```julia
...
Stat.xticks(ticks=TightTicks(data[:DateTime])),
...
```

That being said, I think @DCJones may have fixed this in https://github.com/dcjones/Gadfly.jl/commit/639c885ad0224d504e3d221bd5fb44b8fff83637 but I'm still trying to sort out what's going on there.

**Comment by amellnik** [comment] 2016-01-13 18:01
Also there's apparently a better workaround in https://github.com/dcjones/Gadfly.jl/issues/716

**Comment by IainNZ** [comment] 2016-01-28 21:59
I tried #716, i.e.
`Coord.cartesian(xmin=Date(2014,03,01), xmax=Date(2016,02,01)),`
but got
```
ERROR: LoadError: MethodError: `/` has no method matching /(::Base.Dates.Millisecond, ::Base.Dates.Day)
Closest candidates are:
  /{P<:Base.Dates.Period}(::P<:Base.Dates.Period, ::P<:Base.Dates.Period)
  /(::Base.Dates.Millisecond, ::AbstractFloat)
  /{P<:Base.Dates.Period}(::P<:Base.Dates.Period, ::Real)
  ...
 in resolve at /Users/idunning/.julia/v0.4/Compose/src/measure.jl:411
```

**Comment by IainNZ** [comment] 2016-01-28 22:03
Same error with `TightTicks` as well :/

**Comment by amellnik** [comment] 2016-01-28 22:50
Ah, yeah -- DateTime plays nicely with the '/' operator but not Dates for short time periods.  A heroic effort was put into Gadfly to make Dates and DateTimes work nicely, but there's a few gaps.  

![image](https://cloud.githubusercontent.com/assets/7132414/12661370/1baf4aba-c5ce-11e5-9cbf-b7ae0cdfc901.png)

![image](https://cloud.githubusercontent.com/assets/7132414/12661378/2609bd10-c5ce-11e5-9a68-44192077b864.png)

For years especially this can lead to plots with only a few ticks, so then I do something like:

```julia
ticks = collect(minimum(x_val):Dates.Month(1):maximum(x_vals))
```

Does that work for you?

**Comment by Mattriks** [comment] 2017-04-19 12:12
The issue here is that the user wants to set hard axis limits when x is a `Date` or `DateTime`.  Using `Scale.x_continuous` is not the way to do this, because `Scale.x_continuous` sets soft limits, whereas `Coord.cartesian` sets hard axis limits (this has since been mentioned in the documentation for [`Scale.x_continuous`](http://gadflyjl.org/stable/lib/scales/scale_x_continuous.html)). I think using Dates or DateTimes with `Scale.x_continuous` is not the problem here (it doesn't throw an error on master and behaves as expected).  The issue here is with `Coord.cartesian`, which does lead to an error if x or y are `Date` or `DateTime` objects.  The error actually occurs in `Compose`, and is straight-forward to fix. The following example will currently work with Gadfly master:

```Julia
using Compose
Compose.:/(a::Dates.Millisecond, b::Dates.Day) = a/convert(Dates.Millisecond, b) 
using Gadfly
# x can be a Date or DateTime object:
x = Date(2014,2,1) + Dates.Day.(1:700)
# x = DateTime(2014,2,1) + Dates.Day.(1:700)
y = [1:700;]
coord = Coord.cartesian(xmin=Date(2014,1,1), xmax=Date(2015,12,1))
 p = plot(x=x, y=y, Geom.line, coord, Guide.xticks(orientation=:vertical))
```
![issue784a](https://cloud.githubusercontent.com/assets/18226881/25179157/009a24c8-254c-11e7-9638-521430f8aa80.png)

So I will open a PR in `Compose`.

**Comment by Mattriks** [comment] 2017-04-28 01:22
GiovineItalia/Compose.jl#246 has been merged, so this issue can be closed.

**Closed** 2017-04-28 01:42 UTC
