### ISSUE TITLE
LoadError: syntax: missing comma or ) in argument list

### ISSUE THREAD

**Issue by nmatzke** [GiovineItalia/Gadfly.jl#1314] opened 2019-09-08 23:43 UTC
Hi,

Gadfly, a dependency for PhyloPlots, seemed to be working fine last week, but now, when I try to do "using PhyloPlots" or "using Gadfly", I get this:

```julia
julia> Pkg.add("Gadfly")
 Resolving package versions...
 Installed DiffEqSensitivity ─ v4.0.0
 Installed Mocking ─────────── v0.7.0
 Installed Bijectors ───────── v0.4.0
 Installed Unitful ─────────── v0.17.0
 Installed HTTP ────────────── v0.8.6
  Updating `~/.julia/environments/v1.3/Project.toml`
  [c91e804a] + Gadfly v1.0.1
  Updating `~/.julia/environments/v1.3/Manifest.toml`
  [76274a88] ↑ Bijectors v0.3.2 ⇒ v0.4.0
  [41bf760c] ↑ DiffEqSensitivity v3.3.2 ⇒ v4.0.0
  [cd3eb016] ↑ HTTP v0.8.5 ⇒ v0.8.6
  [78c3b35d] ↑ Mocking v0.6.0 ⇒ v0.7.0
  [1986cc42] ↑ Unitful v0.16.0 ⇒ v0.17.0

julia> using Gadfly
[ Info: Precompiling Gadfly [c91e804a-d5a3-530f-b6f0-dfbca275c004]
ERROR: LoadError: LoadError: syntax: missing comma or ) in argument list
Stacktrace:
 [1] top-level scope at /Users/username/.julia/packages/Gadfly/09PWZ/src/scale.jl:177
 [2] include at ./boot.jl:328 [inlined]
 [3] include_relative(::Module, ::String) at ./loading.jl:1105
 [4] include at ./Base.jl:31 [inlined]
 [5] include(::String) at /Users/username/.julia/packages/Gadfly/09PWZ/src/Gadfly.jl:1
 [6] top-level scope at /Users/username/.julia/packages/Gadfly/09PWZ/src/Gadfly.jl:99
 [7] include at ./boot.jl:328 [inlined]
 [8] include_relative(::Module, ::String) at ./loading.jl:1105
 [9] include(::Module, ::String) at ./Base.jl:31
 [10] top-level scope at none:2
 [11] eval at ./boot.jl:330 [inlined]
 [12] eval(::Expr) at ./client.jl:433
 [13] top-level scope at ./none:3
in expression starting at /Users/username/.julia/packages/Gadfly/09PWZ/src/scale.jl:177
in expression starting at /Users/username/.julia/packages/Gadfly/09PWZ/src/Gadfly.jl:99
ERROR: Failed to precompile Gadfly [c91e804a-d5a3-530f-b6f0-dfbca275c004] to /Users/username/.julia/compiled/v1.3/Gadfly/DvECm_4scsv.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at ./loading.jl:1274
 [3] _require(::Base.PkgId) at ./loading.jl:1024
 [4] require(::Base.PkgId) at ./loading.jl:922
 [5] require(::Module, ::Symbol) at ./loading.jl:917
```

I am using Julia  Version 1.3.0-rc1.0 (2019-08-18), on Mac OS X.

Cheers,
Nick

**Comment by tlnagy** [comment] 2019-09-10 00:17
Can you check out the master branch of both Compose and Gadfly, i.e. in the REPL

```julia
# press ] in the REPL
(v1.2) pkg> dev Gadfly Compose
```

You're using Gadfly v1.0.1 due to hard caps on packages that I bumped in https://github.com/GiovineItalia/Gadfly.jl/pull/1308.

Does that fix the problem? I plan on tagging a new release soon.

**Comment by Red-Portal** [comment] 2019-09-16 16:08
@tlnagy I tried what you suggested but it doesn't help. Same error!

**Comment by bjarthur** [comment] 2019-10-20 13:14
@nmatzke @Red-Portal did you try with a clean test environment?

i cannot reproduce this error on OSX with julia 1.3-rc4 and dev Gadfly and Compose in a fresh test environment:

```
(v1.3) pkg> activate test
Activating new environment at `~/test/Project.toml`

(test) pkg> dev Compose Gadfly
[ Info: Path `/Users/arthurb/.julia/dev/Compose` exists and looks like the correct package, using existing path
[ Info: Path `/Users/arthurb/.julia/dev/Gadfly` exists and looks like the correct package, using existing path
 Resolving package versions...
  Updating `~/test/Project.toml`
  [a81c6b42] + Compose v0.7.4 [`~/.julia/dev/Compose`]
  [c91e804a] + Gadfly v1.1.0 [`~/.julia/dev/Gadfly`]
  Updating `~/test/Manifest.toml`
  [621f4979] + AbstractFFTs v0.4.1
  [7d9fca2a] + Arpack v0.3.1
  [4fba245c] + ArrayInterface v1.2.1
  [13072b0f] + AxisAlgorithms v1.0.0
  [9e28174c] + BinDeps v0.8.10
  [b99e7846] + BinaryProvider v0.5.6
  [00ebfdb7] + CSTParser v0.6.2
  [49dc2e85] + Calculus v0.5.0
  [324d7699] + CategoricalArrays v0.5.5
  [3da002f7] + ColorTypes v0.8.0
  [5ae59095] + Colors v0.9.6
  [bbf7d656] + CommonSubexpressions v0.2.0
  [34da2185] + Compat v2.2.0
  [a81c6b42] + Compose v0.7.4 [`~/.julia/dev/Compose`]
  [8f4d0f93] + Conda v1.3.0
  [d38c429a] + Contour v0.5.1
  [7ad07ef1] + CoupledFields v0.1.0
  [9a962f9c] + DataAPI v1.1.0
  [864edb3b] + DataStructures v0.17.2
  [01453d9d] + DiffEqDiffTools v1.3.0
  [163ba53b] + DiffResults v0.0.4
  [b552c78f] + DiffRules v0.0.10
  [b4f34e82] + Distances v0.8.2
  [31c24e10] + Distributions v0.21.3
  [ffbed154] + DocStringExtensions v0.8.1
  [7a1cc6ca] + FFTW v0.3.0
  [1a297f60] + FillArrays v0.7.2
  [53c48c17] + FixedPointNumbers v0.6.1
  [f6369f11] + ForwardDiff v0.10.3
  [c91e804a] + Gadfly v1.1.0 [`~/.julia/dev/Gadfly`]
  [a1b4810d] + Hexagons v0.2.0
  [9b13fd28] + IndirectArrays v0.5.0
  [a98d9a8b] + Interpolations v0.12.2
  [c8e1da08] + IterTools v1.2.0
  [682c06a0] + JSON v0.21.0
  [e5e0dc1b] + Juno v0.7.2
  [5ab0869b] + KernelDensity v0.5.1
  [d3d80556] + LineSearches v7.0.1
  [4345ca2d] + Loess v0.5.0
  [1914dd2f] + MacroTools v0.5.1
  [442fdcdd] + Measures v0.3.0
  [e89f7d12] + Media v0.5.0
  [e1d29d7a] + Missings v0.4.3
  [d41bc354] + NLSolversBase v7.5.0
  [77ba4419] + NaNMath v0.3.2
  [6fe1bfb0] + OffsetArrays v0.11.1
  [429524aa] + Optim v0.19.3
  [bac558e1] + OrderedCollections v1.1.0
  [90014a1f] + PDMats v0.9.10
  [d96e819e] + Parameters v0.12.0
  [69de0a69] + Parsers v0.3.7
  [85a6dd25] + PositiveFactorizations v0.2.2
  [1fd47b50] + QuadGK v2.0.3
  [c84ed2f1] + Ratios v0.3.1
  [189a3867] + Reexport v0.2.0
  [ae029012] + Requires v0.5.2
  [79098fc4] + Rmath v0.5.0
  [992d4aef] + Showoff v0.3.1
  [a2af1166] + SortingAlgorithms v0.3.1
  [276daf66] + SpecialFunctions v0.7.2
  [90137ffa] + StaticArrays v0.11.0
  [2913bbd2] + StatsBase v0.32.0
  [4c63d2b9] + StatsFuns v0.8.0
  [0796e94c] + Tokenize v0.5.6
  [30578b45] + URIParser v0.4.0
  [81def892] + VersionParsing v1.1.3
  [efce3f68] + WoodburyMatrices v0.4.1
  [2a0f44e3] + Base64 
  [ade2ca70] + Dates 
  [8bb1440f] + DelimitedFiles 
  [8ba89e20] + Distributed 
  [9fa8497b] + Future 
  [b77e0a4c] + InteractiveUtils 
  [76f85450] + LibGit2 
  [8f399da3] + Libdl 
  [37e2e46d] + LinearAlgebra 
  [56ddb016] + Logging 
  [d6f4376e] + Markdown 
  [a63ad114] + Mmap 
  [44cfe95a] + Pkg 
  [de0858da] + Printf 
  [9abbd945] + Profile 
  [3fa0cd96] + REPL 
  [9a3f8284] + Random 
  [ea8e919c] + SHA 
  [9e88b42a] + Serialization 
  [1a1011a3] + SharedArrays 
  [6462fe0b] + Sockets 
  [2f01184e] + SparseArrays 
  [10745b16] + Statistics 
  [4607b0f0] + SuiteSparse 
  [8dfed614] + Test 
  [cf7118a7] + UUIDs 
  [4ec0a83e] + Unicode 

julia> using Gadfly
[ Info: Precompiling Gadfly [c91e804a-d5a3-530f-b6f0-dfbca275c004]

julia> VERSION
v"1.3.0-rc4.1"
```

**Comment by bjarthur** [comment] 2020-01-26 16:05
since i can't reproduce, i will close this (now old) issue.  please re-open if it's still a problem.

**Closed by bjarthur** 2020-01-26 16:05 UTC
Labels: installation
